### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by kkaefer** [mapbox/earcut#10]
In preparation of porting this code to C++, it'd be cool to add type annotations to all variables, and especially parameters.

I haven't used it, but [Flow](http://flowtype.org/) might be a candidate syntax. Alternatively, [TypeScript](http://www.typescriptlang.org/) might be another one.

**Comment by tmcw** [comment]
Having tipped toes into both, Flow is definitely more advanced and has a brighter future. I've run into bugs with both, and Flow's implementation is in Ocaml, which is a negative. There's a [super long issue](https://github.com/facebook/flow/issues/3) about using Flow on vanilla JS and [flotate](https://github.com/jareware/flotate) is the most promising thing to come out of it

**Comment by BergWerkGIS** [comment]
Google's TypeScript equivalent [Dart](https://www.dartlang.org/) might be another candidate?

**Comment by TheMarex** [comment]
Interesting @tmcw. TypeScript seems a lot more mature. What is the advantage of Flow? A more active community? On first glance they seem to have feature parity. Have been thinking about switching most of my JS code to TS.

**Comment by tmcw** [comment]
@TheMarex the basic jist I got is

* TypeScript is not just type annotations, but also adds a few 'features' that are basically ES6 features implemented before they stabilized. Classes & modules that aren't quite-the-same-as-es6-classes-or-modules. The same goes for Dart: you get type annotations, but you also get gross features and a way smaller community of people who know the language.
* Flow annotations are being supported in commonplace es6 converters like [6to5](https://6to5.org/), whereas TypeScript has one implementation
* Both have kind of crazy implementations - TypeScript's is totally non-idiomatic nodejs (since it runs on other platforms), and Flow's is OCaml. But the Flow folks plan to port theirs to JavaScript and given FB's javascript talent (and ms's lack thereof) there's potential for that to be great.
* Flow's [weak mode](http://flowtype.org/docs/existing.html#weak-mode) is extremely useful for transitioning non-annotated code.

That said, [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) is a big tick for the ts side.

**Comment by TheMarex** [comment]
@tmcw thanks for the details. The incompatibility with es6 is really not nice at all. In that light I would probably go with Flow.

**Comment by mourner** [comment]
Don't know how I missed this ticket, sorry. I'll make a filter specifically for mapbox repos I maintain so tickets like this don't get lost, but it's better to cc me explicitly to make sure.

Flow (& flotate which I didn't know about) seems pretty promising considering the pace of development and commitment to ES6 syntax. I'll experiment with it. Not the first time people ask for type annotations of my code — e.g. @incanus had the same gripe when trying to port geojson-vt.

**Comment by mourner** [comment]
@kkaefer poked with TypeScript external definition syntax a bit — would something like this https://gist.github.com/mourner/d310df7767c8a15fed71 help port JS code in future?

**Comment by kkaefer** [comment]
Very much. The biggest hurdle when porting JS code is that some code "reuses" variables and stores different data in them, which is always problematic. Earcut doesn't do that, so the port was fairly straightforward.

**Comment by incanus** [comment]
OMG this would have been cool for geojson-vt. These sound great as we write libs that we know we'll port to a strongly-typed language — or just for our own reference.

**Comment by tmcw** [comment]
News on the Flow side - [they merged support for comment-based annotations](http://flowtype.org/blog/2015/02/20/Flow-Comments.html), making it possible to annotate without a build step.

**Comment by mourner** [comment]
Did https://github.com/mapbox/earcut/blob/typed/src/earcut.d.ts a while back, not actionable for now I guess.
