### ISSUE TITLE
Flat array of points

### ISSUE THREAD

**Issue by englercj** [mapbox/earcut#18]
This library looks awesome, my only issue with it is the format the data input is in. Up until now we have been using `PolyK` which has worked OK but is kind of slow and buggy.

I want to switch to this library but our data is a flat array of 2D coords (`[x, y, x, y, x, y, ...]`) and I would have to convert it to the format used here in order to make it work with this lib. The GC churn that would be caused by creating so many array objects is not desired. Is there anyway for this library to support a flat-array of coords syntax?

**Comment by mourner** [comment]
Sorry I missed your issue somehow... This makes sense, I'll think about it, although it's not trivial since the algorithm depends on keeping references to points. Keeping indexes to original input array would be an alternative, but it may hit performance due to increased access time.

**Comment by englercj** [comment]
Hmm, I would expect performance to increase using a flat array since you need to deference less. I'm interested to see how this works out.

**Comment by mourner** [comment]
Curious to try that out too. @englercj btw, just wondering, what app/lib are you going to use earcut in?

**Comment by englercj** [comment]
We want to try and use it in [Pixi.js](https://github.com/GoodBoyDigital/pixi.js).

**Comment by mourner** [comment]
Ha, that's awesome!

**Comment by mourner** [comment]
@englercj OK so I decided to test out this idea on a stripped, barebones earcut version (no holes/degenerates/etc. to move fast) and it looks pretty promising — here's how it looks: https://github.com/mapbox/earcut/commit/2c3926a0c06855a1f6f8c0838f9d14cd8964a39a

For the dude without holes test case, it's ~8% faster than non-flat output and ~12% than non-flat indexed output. For polygons with holes, I'll probably have to update the API to accept a fully flat input array for all rings and additionally an array of hole indices in this array — does this make sense? A nice advantage of this is that we can make earcut always have indexed output (since there's no perf hit), and also reference the original input array instead of forming a new one.

So the API would look like this:

```js
var triangles = earcut([10,0, 0,50, 60,60, 70,10]);
// [0,1,3, 2,3,0]
```

If there are holes, there would be an array like `[1, 5, ...]` where each number represents the index where the new ring starts in the flat coordinates array. Additionally `earcut` now needs to accept optional `dimensions` argument that's `2` by default since we can't infer this from input anymore.

@sctf4 in your case, would this breaking API change be OK?

**Comment by mourner** [comment]
Also cc @Kosta-Github

**Comment by englercj** [comment]
Sounds promising, I like the idea of an API like `earcut(polygonPoints, deminsions, hole1Points, hole2Points, ...)`.

**Comment by mourner** [comment]
@englercj no, it'd be more like `earcut(polygonData[, holeIndices, dimensions])`
```

**Comment by Kosta-Github** [comment]
Yes, would work for me as well.

**Comment by englercj** [comment]
@mourner Ah, gotcha I misunderstood!

**Comment by sctf4** [comment]
Sounds interesting - definitely worth a try for us too!

If I understand correctly we pass an array of ring data with all hole 
data concatenated at the end, then pass indices just for the start 
position of the holes?

Currently we don't use indexed output so we'll have to process the 
indices to generate triangle vertices... but this probably does not have 
a huge perf impact.

Look forward to trying it :)

**Comment by mourner** [comment]
@sctf4 yeah, the overhead of converting the output shouldn't be noticeable. But consider using indexed rendering — in theory, it's faster since there's much less data to upload to the GPU and vertex shaders do 3 times less work.

My goal here is to change the API to make it fit the WebGL use case as efficiently as possible.

**Comment by mourner** [comment]
Can you guys try out https://github.com/mapbox/earcut/pull/19? Is it any good?

**Comment by englercj** [comment]
Pretty busy tonight and tomorrow night, but I will be doing pixi work this weekend and can check it out.
