### ISSUE TITLE
Vertex missing from triangle output

### ISSUE THREAD

**Issue by robhawkes** [mapbox/earcut#22]
I've found that some of the vertices in my polygons are being ignored when run through earcut, resulting in less triangles than would be expected.

For example, take the following points:

```
[68238.985, 268.575, 68248.747, 268.512, 68248.747, 259.248, 68238.985, 259.248, 68238.338, 259.248, 68238.338, 268.58, 68238.985, 268.575]
```

There are 6 unique vertices (7 minus the duplicated start/end vertex), which when run through earcut produce the following 3 triangles:

```
[5, 4, 2, 2, 1, 6, 6, 5, 2]
```

Which looks like this (notice how the vertex second from left at the bottom is part of no face):

![](http://cl.ly/image/3105303Z3D38/Screen%20Shot%202015-05-07%20at%2013.00.18.png)

When the same polygon is run through poly2tri the results are as per expected; 4 triangles using all vertices:

![](http://cl.ly/image/0u1Y200N3415/Screen%20Shot%202015-05-07%20at%2013.03.42.png)

Is this expected with earcut, or is something wrong? I notice in the readme that it's suggested that earcut can sacrifice triangulation quality so I want to be sure that's the cause before moving to another triangulation approach for now.

**Comment by mourner** [comment]
This is expected with earcut because it removes all collinear and duplicate points prior to triangulation, assuming they are not useful for the end result and can only introduce degeneracies. 

Can you clarify why that colinear vertice at the bottom is needed in the output? Is it because it's actually not collinear when considering the 3-rd axis and so visually significant?

**Comment by robhawkes** [comment]
That's right, when adding the 3rd axis back in the difference is minute but enough to be important – skipping the vertex introduces a gap between this polygon and the one next to it.

If this is expected behaviour then I'll give one of the other triangulation libraries a go for this 3D work, though I'm impressed with earcut for my 2D needs in the future.

**Comment by mourner** [comment]
So, removing collinear points filtering introduces lots of test failures because it helps deal with degenerate cases. Also, I don't think poly2tri.js would help you in every case since triangulation could end up being not as favorable in regards to the added back 3rd axis, and it will in other cases. I will close this for now because I don't have a solution, but if you have further thoughts on this, let me know.

**Comment by mourner** [comment]
@robhawkes here's one more example to illustrate my point: imagine you have a square polygon (4 points), where 3 points are z=0 and one is z=100. There are two ways to triangulate this: split by diagonal through the extruded point, or split by diagonal through adjacent points. Topologically (in 3D) those two results will be completely different, and there's no definition of what's actually a correct triangulation.

The algorithm can't handle things like that automatically because the result is not even mathematically defined.
