### ISSUE TITLE
Incorrect triangulation in case of a hole fully inside another one

### ISSUE THREAD

**Issue by germanz** [mapbox/earcut#94]
The following polygon with two holes (one inside another one) produces wrong triangulation result:
```
const earcut = require('earcut');
const poly = {
  'type': 'Feature',
  'geometry': {
    'type': 'Polygon',
    'coordinates':  [
      [[10, -10], [10, 10], [-10, 10], [-10, -10], [10, -10]],
      [[5, -5], [-5, -5], [-5, 5], [5, 5], [5, -5]],
      [[3, -3], [3, 3], [-3, 3], [-3, -3], [3, -3]]
    ]
  }
};
const flatpoly = earcut.flatten(poly.geometry.coordinates);

console.log(JSON.stringify(earcut(flatpoly.vertices, flatpoly.holes, flatpoly.dimensions)));
// logs [5,6,3,3,13,12,0,8,5,0,5,3,14,13,3,8,0,1,2,3,6,7,8,1,2,6,7,7,1,2]
```

Expected:
![expected](https://user-images.githubusercontent.com/2526045/35333869-9f4d1b48-0110-11e8-8cbb-e1bc463b88af.png)

Result:
![result](https://user-images.githubusercontent.com/2526045/35333450-1b97805a-010f-11e8-8f6a-da18b4f061ed.png)

**Comment by mourner** [comment]
This is by design — Earcut doesn't classify polygon rings according to their structure/nesting, it only works with single polygons that are defined as an outer ring and holes that relate to that ring. In that sense, this particular example is actually two polygons — one outer one with a hole, and another small one, which means you'd have to triangulate those two separately.

**Comment by germanz** [comment]
Got it! Thanks.
